---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  # chef_version: '12.21.31'
  chef_version: <%= ENV['CHEF_VERSION'] || 'stable' %>
  volumes:
    - <%= File.join(__dir__, '.kitchen', 'cache') %>:/opt/kitchen/cache
  ports: [
    '8080',
    '9990',
    '8082',
    '9992',
    ]

transport:
  name: dokken

provisioner:
  name: dokken
  # Config-option only support on Chef 12.13+
  # chef_options: '--config-option file_cache_path=/tmp/chef -z'
  chef_options: '--config-option lockfile=/tmp/chef-client-running.pid -z'
  chef_log_level: 'info'

verifier:
  name: inspec

#
# Platforms
#
platforms:
- name: amazon
  driver:
    image: dokken/amazonlinux-2
    pid_one_command: /usr/lib/systemd/systemd

- name: centos-7
  driver:
    image: dokken/centos-7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd

- name: ubuntu-14.04
  driver:
    image: ubuntu:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - >
        ENV container docker
        RUN /usr/bin/apt-get update
        && /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y
        && /usr/bin/apt-get install ca-certificates cron -y

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd

#
# Test Suites
#
suites:
  - name: 'default'
    run_list:
      - recipe[test::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      # wildfly:
      #  version: '11.0.0'
      #  # => Disable System Tuning
      #  system_tuning: false
    includes: [
      'amazon',
      'centos-7',
      'ubuntu-14.04',
      'ubuntu-16.04',
      ]

  - name: 'resource'
    run_list:
      - recipe[test::resource]
    verifier:
      inspec_tests:
        - test/integration/resource
    attributes:
      # wildfly:
      #  version: '11.0.0'
      #  # => Disable System Tuning
      #  system_tuning: false
    includes: [
      'amazon',
      'centos-7',
      'ubuntu-14.04',
      'ubuntu-16.04'
      ]

  - name: 'api'
    run_list:
      - recipe[test::api]
    verifier:
      inspec_tests:
        - test/integration/api
    attributes:
      wildfly:
        mysql:
          enabled: true
        postgresql:
          enabled: true
    includes: [
      'amazon',
      'centos-7',
      'ubuntu-14.04',
      'ubuntu-16.04'
      ]
